In [114]:
import numpy as np
import pandas as pd 
import seaborn as sns

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [3]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

a*b

array([ 2,  6, 12, 20])

In [5]:
# NumPy Array'i Oluşturmak

np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [6]:
#sifirdan array olusturma 

np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [8]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [9]:
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.random.randint(0,10, (3,3))

array([[6, 5, 6],
       [0, 0, 0],
       [3, 2, 4]])

In [13]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [14]:
b = a.reshape((1,9))

b.ndim

2

In [16]:
a = np.array([[1,2,3], 
              [4,5,6]])

np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [17]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [20]:
# Array Ayırma (Splitting)

x = np.array([1,2,3,99,99,3,2,1])
# np.split(x, [3,5])
a,b,c = np.split(x, [3,5])
a

array([1, 2, 3])

In [21]:
#iki boyutlu ayırma
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [23]:
ust, alt = np.vsplit(m, [2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [25]:
sag, sol = np.hsplit(m, [2])

sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [29]:
# Array Sıralama (Sorting)

v = np.array([2,1,4,3,5])

v.sort() # ya da np.sort(v) v ye gerek kalmaz
v

array([1, 2, 3, 4, 5])

In [33]:
a = np.random.randint(10, size = 10)
a

array([7, 7, 8, 3, 9, 5, 6, 9, 8, 0])

In [37]:
a[-2]

8

In [38]:
a[0] = 100
a

array([100,   7,   8,   3,   9,   5,   6,   9,   8,   0])

In [39]:
m = np.random.randint(10, size = (3,5))
m

array([[0, 7, 2, 7, 6],
       [0, 8, 1, 6, 6],
       [5, 6, 3, 0, 6]])

In [40]:
m[1,1]

8

In [41]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
a[1:3]

array([21, 22])

In [45]:
a[3::2]

array([23, 25, 27, 29])

In [46]:
#iki boyutlu slice islemleri

m = np.random.randint(10, size = (5,5))
m

array([[7, 4, 3, 8, 7],
       [3, 0, 6, 9, 3],
       [2, 8, 8, 8, 0],
       [5, 5, 7, 5, 6],
       [7, 4, 3, 7, 8]])

In [47]:
m[:,2] #sutun

array([3, 6, 8, 7, 3])

In [48]:
m[0,:]

array([7, 4, 3, 8, 7])

In [49]:
m[0:2, 0:3]

array([[7, 4, 3],
       [3, 0, 6]])

In [50]:
v = np.array([1, 2, 3, 4, 5])

v < 3

array([ True,  True, False, False, False])

In [52]:
v[v >= 3]

array([3, 4, 5])

In [53]:
v * *2 # np.power(v, 3)
# np.mod(v, 2)  ==  v % 2

array([ 2,  4,  6,  8, 10])

In [54]:
v

array([1, 2, 3, 4, 5])

In [55]:
np.mean(v)

3.0

In [56]:
v.sum()

15

In [57]:
v.min()

1

In [62]:
seri = pd.Series([10,88,3,4,5])
seri

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [63]:
type(seri)

pandas.core.series.Series

In [64]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [65]:
seri.size

5

In [66]:
seri.ndim

1

In [67]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [68]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [69]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [72]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])
seri

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [73]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [76]:
sozluk = {"reg":10, "log":11, "cart": 12}
seri = pd.Series(sozluk)
seri

reg     10
log     11
cart    12
dtype: int64

In [77]:
seri.index

Index(['reg', 'log', 'cart'], dtype='object')

In [79]:
list(seri.items())

[('reg', 10), ('log', 11), ('cart', 12)]

In [80]:
seri.values

array([10, 11, 12], dtype=int64)

In [81]:
"reg" in seri

True

In [82]:
seri["reg"]

10

In [84]:
seri[["log", "reg"]]

log    11
reg    10
dtype: int64

In [85]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

sozluk = {"var1": s1, "var2": s2, "var3": s3}
sozluk

{'var1': array([3, 3, 8, 4, 3]),
 'var2': array([5, 3, 0, 9, 3]),
 'var3': array([5, 7, 2, 8, 6])}

In [88]:
df = pd.DataFrame(sozluk)
df[0:1]

var1  var2  var3
0     3     5     5

In [89]:
df.index = ["a","b","c","d","e"]
df

var1  var2  var3
a     3     5     5
b     3     3     7
c     8     0     2
d     4     9     8
e     3     3     6

In [91]:
df.drop("a", axis = 0, inplace = True)
df

var1  var2  var3
b     3     3     7
c     8     0     2
d     4     9     8
e     3     3     6

In [93]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df


var1  var2  var3
0    15     1    27
1     1    21    13
2    11     1    19
3     7    20     8
4    21    15    11
5    13     2    14
6    15    15     7
7    10    20    23
8    11     3    17
9    12    13    23

In [95]:
df.loc[0:3]


var1  var2  var3
0    15     1    27
1     1    21    13
2    11     1    19
3     7    20     8

In [96]:
df.iloc[0:3]

var1  var2  var3
0    15     1    27
1     1    21    13
2    11     1    19

In [97]:
df.loc[0:3, "var3"]

0    27
1    13
2    19
3     8
Name: var3, dtype: int32

In [98]:
df[df.var1 > 15]

var1  var2  var3
4    21    15    11

In [102]:
df[(df.var1 > 15) & (df.var3 < 45)]

var1  var2  var3
4    21    15    11

In [103]:
df.loc[(df.var1 > 15), ["var1","var2"]]

var1  var2
4    21    15

In [104]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
4    21    15

In [106]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [107]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [108]:
pd.merge(df1, df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [109]:
df3 = pd.merge(df1, df2)
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [110]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [111]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [112]:
df1


calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [113]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

In [ ]:
Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [115]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [116]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [117]:
df.groupby("gruplar").aggregate([min, np.median, max])

C:\Users\asli_\AppData\Local\Temp\ipykernel_3464\2594767197.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("gruplar").aggregate([min, np.median, max])
C:\Users\asli_\AppData\Local\Temp\ipykernel_3464\2594767197.py:1: FutureWarning: The provided callable <function median at 0x000002200D6EAE80> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby("gruplar").aggregate([min, np.median, max])
C:\Users\asli_\AppData\Local\Temp\ipykernel_3464\2594767197.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [123]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [124]:
df.groupby("gruplar").filter(filter_func)

Empty DataFrame
Columns: [gruplar, degisken1, degisken2]
Index: []

In [125]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64